USE solace_demo;

CREATE TABLE notes (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  active BOOLEAN NOT NULL DEFAULT 1,
  title VARCHAR(80) NOT NULL,
  body VARCHAR(300) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY pk_notes (id)
);

